### 1. Problem Undestanding
Here we will look at a Data Science challenge within the IMDB space. For our model fitting choose the f1-score metric.

Results of exploring for model we will provided in table model_search_result

In [283]:
model_search_result = pd.DataFrame(columns=['Model','F1 test', 'F1 train'], )

### Import libraries & data

In [228]:
# import libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.metrics import SCORERS
from sklearn.metrics import f1_score

In [229]:
# import & display data
data = pd.read_csv('data/IMDB_Dataset.csv')

### The Data
Our training set has 50K movie reviews for natural language processing.  This is a dataser for binary sentiment classification. 
For more dataset information, please go through the following link,
https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [230]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### Check statistics

In [231]:
data.count()

review       50000
sentiment    50000
dtype: int64

In [232]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [233]:
data.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

#### replace the categoric values from 'sentiment' to numeric

In [234]:
data['sentiment'] = data['sentiment'].replace({'positive' : 1, 'negative' : 0})

In [235]:
data.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

##### Splitting data for train and test sets

In [236]:
X = data['review']
y = data['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42, stratify = y)

#### Applying CountVectorizer for convert a collection of text documents to a matrix of token counts

In [237]:
# Instantiate the vectorizer
count_vectorizer = CountVectorizer()
count_vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [238]:
# fit and transform on it the training features
count_vectorizer.fit(X_train)
X_train_features = count_vectorizer.transform(X_train)

#transform the test features to sparse matrix
X_test_features = count_vectorizer.transform(X_test)

In [239]:
count_vectorizer.vocabulary_

{'if': 37842,
 'you': 86728,
 'want': 84104,
 'to': 78262,
 'see': 68347,
 'true': 79727,
 'thriller': 77741,
 'rent': 64046,
 'this': 77614,
 'it': 40310,
 'not': 53862,
 'from': 30393,
 'the': 77357,
 'director': 21664,
 'or': 55143,
 'screenwriter': 67998,
 'of': 54587,
 'scream': 67965,
 'doesn': 22601,
 'feature': 27992,
 'overacting': 55714,
 'overpaid': 55871,
 'tv': 80104,
 'actors': 1968,
 'passing': 56888,
 'off': 54591,
 'as': 5232,
 'stars': 73346,
 'and': 3844,
 'is': 40193,
 'run': 66244,
 'mill': 49934,
 'special': 72389,
 'effects': 24481,
 'bonanza': 9680,
 'instead': 39398,
 'll': 45620,
 'get': 31766,
 'top': 78545,
 'notch': 53871,
 'edgy': 24358,
 'very': 82974,
 'strong': 74270,
 'in': 38390,
 'violence': 83341,
 'yet': 86597,
 'thrilling': 77743,
 'nailbiter': 52371,
 'one': 54897,
 'first': 28778,
 'best': 8259,
 'columbos': 15800,
 'starring': 73342,
 'robert': 65419,
 'culp': 18656,
 'ray': 62750,
 'milland': 49937,
 'appeared': 4541,
 'on': 54880,
 'another': 4160,
 'columbo': 15799,
 'did': 21331,
 'several': 68906,
 'other': 55450,
 'villains': 83255,
 'including': 38534,
 'patrick': 57023,
 'mcgoohan': 48665,
 'william': 85297,
 'shatner': 69256,
 'jack': 40452,
 'cassidy': 12847,
 'also': 3330,
 'made': 46872,
 'later': 44195,
 'appearance': 4538,
 'br': 10234,
 'convinced': 17147,
 'his': 36219,
 'beautiful': 7543,
 'wife': 85196,
 'played': 58888,
 'by': 11709,
 'patricia': 57020,
 'crowley': 18428,
 'having': 35111,
 'an': 3738,
 'affair': 2402,
 'so': 71580,
 'he': 35208,
 'hires': 36202,
 'investigate': 39944,
 'has': 34953,
 'blackmailing': 8876,
 'business': 11574,
 'side': 70059,
 'gives': 32162,
 'fake': 27443,
 'report': 64184,
 'threatens': 77721,
 'with': 85585,
 'real': 62854,
 'she': 69304,
 'pay': 57142,
 'up': 82017,
 'they': 77515,
 'into': 39810,
 'huge': 37240,
 'fight': 28454,
 'home': 36571,
 'winds': 85392,
 'murdered': 51951,
 'enter': 25640,
 'does': 22599,
 'everything': 26476,
 'can': 12145,
 'case': 12789,
 'offering': 54620,
 'him': 36113,
 'job': 41176,
 'but': 11610,
 'beginning': 7740,
 'excellent': 26630,
 'episode': 25837,
 'was': 84218,
 'movie': 51570,
 'about': 1535,
 'civi': 14793,
 'war': 84112,
 'my': 52170,
 'aunt': 5850,
 'actually': 1981,
 'extra': 27131,
 'justin': 41660,
 'madeline': 46880,
 'wedding': 84495,
 'scene': 67507,
 'uncle': 80705,
 'horse': 36920,
 'script': 68030,
 'genuine': 31631,
 'accurate': 1778,
 'costumes': 17579,
 'were': 84695,
 'tastefully': 76519,
 'done': 22789,
 'seqence': 68714,
 'order': 55198,
 'even': 26419,
 'accents': 1679,
 'good': 32689,
 'dearly': 19613,
 'love': 46147,
 'swayze': 75584,
 'james': 40599,
 'ried': 65059,
 'choices': 14306,
 'had': 34220,
 'great': 33254,
 'supporting': 75219,
 'cast': 12856,
 'civil': 14796,
 'favorite': 27908,
 'thing': 77563,
 'american': 3571,
 'history': 36244,
 'movies': 51596,
 'have': 35098,
 'seen': 68380,
 'quite': 61970,
 'few': 28333,
 'sequal': 68715,
 'north': 53810,
 'south': 72166,
 'book': 9788,
 'took': 78502,
 'cake': 11900,
 'haven': 35100,
 'soon': 71972,
 'possible': 59706,
 'eduation': 24404,
 'probably': 60551,
 'new': 53136,
 'zealands': 87004,
 'worst': 85995,
 'ever': 26440,
 'jokes': 41278,
 'are': 4848,
 'funny': 30659,
 'used': 82210,
 'just': 41647,
 'plain': 58772,
 'corny': 17398,
 'acting': 1935,
 'bad': 6435,
 'though': 77680,
 'there': 77467,
 'story': 73954,
 'uninteresting': 81368,
 'boring': 9960,
 'more': 51210,
 'cheese': 13904,
 'then': 77427,
 'pizza': 58721,
 'huts': 37509,
 'lovers': 46174,
 'kind': 42661,
 'like': 45230,
 'been': 7665,
 'do': 22488,
 '000': 1,
 'times': 78046,
 'before': 7704,
 'watched': 84280,
 'when': 84876,
 'came': 12056,
 'could': 17623,
 'only': 54924,
 'stand': 73223,
 '30': 725,
 'minutes': 50189,
 'sucks': 74759,
 'watch': 84272,
 'paint': 56248,
 'dry': 23544,
 'remember': 63904,
 'seeing': 68360,
 'early': 24113,
 '90': 1140,
 'uk': 80410,
 'hooked': 36752,
 'international': 39678,
 'scope': 67858,
 'production': 60639,
 'breathtaking': 10506,
 'watching': 84286,
 'how': 37109,
 'characters': 13634,
 'develop': 21037,
 'through': 77768,
 'five': 28850,
 'hours': 37057,
 'runs': 66262,
 'for': 29568,
 'magnificent': 47003,
 'scenes': 67513,
 'set': 68856,
 'pakistan': 56276,
 'afghanistan': 2465,
 'particular': 56801,
 'interest': 39608,
 'viewer': 83177,
 'sense': 68614,
 'grounds': 33597,
 'eye': 27206,
 'view': 83172,
 'culture': 18677,
 'vibe': 83038,
 'these': 77494,
 'countries': 17700,
 'during': 23883,
 'closing': 15233,
 'stages': 73117,
 'cold': 15617,
 'fazal': 27937,
 'helen': 35533,
 'really': 62884,
 'well': 84638,
 'throughout': 77772,
 'series': 68792,
 'rivals': 65307,
 'modern': 50677,
 'shows': 69829,
 'sopranos': 72021,
 'six': 70534,
 'feet': 28059,
 'under': 80825,
 'area': 4849,
 'vhs': 83024,
 'goes': 32534,
 'dvd': 23947,
 '10': 49,
 'quality': 61755,
 'bargain': 6986,
 'thought': 77682,
 'soderbergh': 71680,
 'version': 82957,
 'too': 78498,
 'clearly': 15020,
 'owes': 56034,
 'masterpiece': 48177,
 'debt': 19690,
 'heart': 35310,
 'pounding': 59826,
 'erotic': 26008,
 'drama': 23215,
 'words': 85890,
 'that': 77337,
 'come': 15845,
 'mind': 50036,
 'think': 77574,
 'secret': 68278,
 'games': 31036,
 'becomes': 7595,
 'film': 28519,
 'along': 3288,
 'at': 5568,
 'point': 59175,
 'blew': 9090,
 'me': 48828,
 'away': 6136,
 'didn': 21345,
 'expect': 26879,
 'delightful': 20223,
 'encounter': 25326,
 'call': 11979,
 'girl': 32098,
 'her': 35716,
 'customer': 18830,
 'what': 84818,
 'most': 51396,
 'lesbian': 44867,
 'husband': 37473,
 'should': 69768,
 'listened': 45493,
 'perhaps': 57637,
 'wouldn': 86018,
 'gone': 32668,
 'journey': 41398,
 'turned': 80024,
 'out': 55515,
 'cost': 17548,
 'them': 77410,
 'end': 25351,
 'exciting': 26677,
 'ride': 65027,
 'go': 32431,
 'scratch': 67952,
 'african': 2496,
 'created': 18065,
 'rhythms': 64935,
 'jawbone': 40773,
 'ass': 5383,
 'virgin': 83363,
 'islanders': 40247,
 'welded': 84629,
 'oil': 54715,
 'drums': 23527,
 'ear': 24098,
 'pleasing': 58952,
 'steel': 73498,
 'bands': 6801,
 'urban': 82125,
 'dj': 22455,
 'itch': 40326,
 'pursuit': 61545,
 'methods': 49560,
 'creative': 18072,
 'expression': 27051,
 'wholly': 85070,
 'unnarrated': 81532,
 'documentary': 22556,
 'which': 84902,
 'will': 85278,
 'take': 76168,
 'hip': 36168,
 'hop': 36797,
 'rap': 62513,
 'movement': 51563,
 'explore': 27001,
 'genesis': 31555,
 'turntablism': 80039,
 'art': 5130,
 'scratching': 67959,
 'vinyl': 83327,
 'ultimate': 80450,
 'mc': 48521,
 'contempo': 16920,
 'entertainment': 25661,
 'reveals': 64703,
 'some': 71864,
 'surprisingly': 75337,
 'intelligent': 39522,
 'articulate': 5167,
 'scratchers': 67955,
 'startlingly': 73361,
 'unique': 81384,
 'abilities': 1469,
 'concert': 16347,
 'competition': 16127,
 'where': 84881,
 'beat': 7496,
 'meets': 49023,
 'street': 74132,
 'stuff': 74370,
 'anyone': 4372,
 'interested': 39609,
 'grass': 33159,
 'roots': 65776,
 'ghetto': 31819,
 'gutter': 34040,
 'movements': 51564,
 'sound': 72125,
 'trust': 79771,
 'junagadh75': 41588,
 'review': 64760,
 'compelling': 16103,
 'moving': 51606,
 'roughest': 65946,
 'brutally': 11040,
 'way': 84382,
 'file': 28487,
 'unforgettable': 81199,
 'meat': 48885,
 'films': 28573,
 'howl': 37123,
 'moon': 51103,
 'pixote': 58714,
 'gets': 31776,
 'your': 86751,
 'nervous': 53030,
 'system': 75959,
 'elevates': 24809,
 'despite': 20863,
 'pain': 56233,
 'screen': 67983,
 'here': 35742,
 'unrelated': 81698,
 'list': 45488,
 'same': 66814,
 'engaged': 25442,
 'destroyed': 20899,
 'transformed': 79066,
 'inspired': 39372,
 'resonated': 64423,
 'category': 12972,
 'transcends': 79033,
 'nerdy': 53016,
 'ten': 76968,
 'lists': 45507,
 'seek': 68361,
 'perfection': 57604,
 'woman': 85732,
 'influence': 38998,
 'wiseblood': 85525,
 'wages': 83881,
 'fear': 27961,
 'saint': 66651,
 'bones': 9707,
 'blue': 9306,
 'many': 47656,
 'us': 82194,
 'be': 7418,
 'supernatural': 75131,
 'element': 24790,
 'plot': 59014,
 'let': 44898,
 'tale': 76205,
 'heaps': 35289,
 'charm': 13703,
 'kindly': 42677,
 'cased': 12790,
 'crab': 17869,
 'shell': 69371,
 'we': 84410,
 'presented': 60260,
 'town': 78806,
 'economically': 24299,
 'depressed': 20624,
 'struggling': 74307,
 'find': 28625,
 'anything': 4375,
 'happy': 34712,
 'beau': 7523,
 'bridges': 10640,
 'character': 13613,
 'against': 2542,
 'family': 27551,
 'increase': 38616,
 'nil': 53433,
 'bank': 6831,
 'balance': 6605,
 'brother': 10925,
 'law': 44347,
 'who': 85054,
 'sold': 71769,
 'big': 8492,
 'chain': 13432,
 'secretly': 68287,
 'hates': 35030,
 'willing': 85308,
 'rub': 66088,
 'nose': 53835,
 'onofrio': 54927,
 'finds': 28632,
 'rather': 62631,
 'surface': 75284,
 'bubba': 11088,
 'lifestyle': 45175,
 'cramped': 17932,
 'look': 45919,
 'after': 2511,
 'blessed': 9079,
 'baby': 6311,
 'joey': 41215,
 'itching': 40330,
 'escape': 26076,
 'shackles': 69021,
 'dead': 19563,
 'hick': 35942,
 'their': 77395,
 'boss': 10021,
 'down': 23088,
 'much': 51695,
 'because': 7569,
 'lack': 43664,
 'customers': 18831,
 'haunted': 35076,
 'memories': 49207,
 'father': 27834,
 'builds': 11233,
 'tension': 77045,
 'towards': 78797,
 'own': 56038,
 'attempt': 5701,
 'self': 68482,
 'destruction': 20907,
 'seemed': 68373,
 'personify': 57804,
 'curse': 18770,
 'lives': 45585,
 'lost': 46056,
 'sea': 68139,
 'believed': 7866,
 'drowned': 23485,
 'freak': 30100,
 'accident': 1707,
 'miraculous': 50201,
 'restoration': 64505,
 'portuguese': 59645,
 'trawlermen': 79257,
 'whose': 85110,
 'boat': 9414,
 'built': 11236,
 'launched': 44280,
 'symbolic': 75822,
 'angelic': 3949,
 'crew': 18155,
 'sign': 70140,
 've': 82697,
 'waiting': 83933,
 'all': 3144,
 'decide': 19766,
 'give': 32155,
 'life': 45148,
 'last': 44171,
 'throw': 77777,
 'dice': 21284,
 'brooding': 10893,
 'mood': 51089,
 'work': 85900,
 'excelled': 26627,
 'holding': 36457,
 'our': 55502,
 'attention': 5715,
 'brilliantly': 10709,
 'shipping': 69563,
 'news': 53178,
 'parallels': 56583,
 'lead': 44440,
 'suspect': 75410,
 'touch': 78732,
 'remake': 63873,
 'signs': 70172,
 'its': 40354,
 'simpler': 70311,
 'less': 44880,
 'contrived': 17064,
 'star': 73286,
 'performances': 57624,
 'working': 85916,
 'craft': 17902,
 'than': 77312,
 'noticed': 53898,
 'ossessa': 55415,
 'released': 63784,
 'english': 25471,
 'titles': 78204,
 'eeriest': 24462,
 'certainly': 13359,
 'eerie': 24460,
 'midnight': 49761,
 'horror': 36904,
 'show': 69796,
 'italian': 40312,
 'rip': 65213,
 'offs': 54646,
 'exorcist': 26856,
 'appreciate': 4623,
 'humor': 37355,
 'time': 78024,
 'sleazy': 70902,
 'naive': 52386,
 'pathetic': 56980,
 'sometimes': 71889,
 'danila': 19246,
 'stella': 73555,
 'carnacina': 12598,
 'student': 74354,
 'old': 54777,
 'church': 14558,
 'statue': 73419,
 'going': 32556,
 'restore': 64507,
 'wooden': 85791,
 'christ': 14428,
 'demonic': 20379,
 'maybe': 48458,
 'already': 3323,
 'overcome': 55751,
 'evil': 26504,
 'fighting': 28458,
 'planning': 58811,
 'dark': 19324,
 'deeds': 19892,
 'face': 27298,
 'infinite': 38966,
 'torment': 78617,
 'dates': 19432,
 '15th': 222,
 'century': 13327,
 'impressed': 38317,
 'mastery': 48188,
 'shown': 69824,
 'sculptor': 68100,
 'seems': 68378,
 'almost': 3275,
 'alive': 3136,
 'parents': 56669,
 'mother': 51417,
 'luisa': 46365,
 'lucretia': 46324,
 'dissolute': 22248,
 'care': 12477,
 'keeping': 42217,
 'appearances': 4539,
 'mario': 47836,
 'chris': 14421,
 'avram': 6102,
 'observes': 54383,
 'disenchanted': 21920,
 'eyes': 27230,
 'assume': 5485,
 'human': 37288,
 'form': 29718,
 'ivan': 40373,
 'rassimov': 62600,
 'possess': 59693,
 'carnal': 12600,
 'spiritual': 72632,
 'amazing': 3487,
 'poor': 59470,
 'now': 53973,
 'suffer': 74791,
 'torments': 78623,
 'hell': 35550,
 'lovely': 46170,
 'ravished': 62725,
 'violated': 83334,
 'possessed': 59694,
 'devil': 21076,
 'following': 29474,
 'orders': 55204,
 'try': 79791,
 'seduce': 68335,
 'others': 55452,
 'ain': 2765,
 'emulating': 25258,
 'feels': 28054,
 'pleasure': 58955,
 'lover': 46172,
 'whips': 84949,
 'bunch': 11354,
 'roses': 65843,
 'ridiculous': 65048,
 'sublime': 74559,
 'despair': 20833,
 'narrow': 52537,
 'streets': 74141,
 'small': 71170,
 'screaming': 67969,
 'luigi': 46363,
 'pistilli': 58643,
 'performance': 57623,
 'usual': 82239,
 'intense': 39535,
 'exorcism': 26853,
 'particularlly': 56805,
 'final': 28600,
 'battle': 7314,
 'amateurish': 3467,
 'enhance': 25496,
 'fun': 30596,
 'emotion': 25178,
 'got': 32875,
 'looks': 45932,
 'fresh': 30235,
 'innocent': 39212,
 'factor': 27347,
 'adds': 2072,
 'naked': 52402,
 'explored': 27002,
 'natural': 52634,
 'beauty': 7550,
 'sleaze': 70892,
 'companion': 16067,
 'nude': 54031,
 'would': 86016,
 'recommend': 63143,
 'malabimba': 47204,
 'uncut': 80807,
 'digitally': 21444,
 'restored': 64508,
 'malocchio': 47317,
 'main': 47103,
 'source': 72152,
 'inspiration': 39368,
 'instance': 39389,
 'rosemary': 65826,
 'taken': 76177,
 'account': 1758,
 'completely': 16162,
 'over': 55708,
 'plenty': 58979,
 'gorgeous': 32815,
 'spanish': 72285,
 'actresses': 1972,
 'drooling': 23454,
 'make': 47175,
 'any': 4358,
 'right': 65108,
 'might': 49798,
 'feel': 28047,
 'moved': 51558,
 'diabolical': 21192,
 'sect': 68292,
 'possession': 59697,
 'murders': 51958,
 'investigation': 39948,
 'women': 85747,
 'around': 5046,
 'wild': 85225,
 'liked': 45234,
 'ring': 65172,
 'darkness': 19341,
 'un': 80511,
 'ombra': 54846,
 'nell': 52955,
 'found': 29864,
 'alternative': 3363,
 'market': 47864,
 'search': 68190,
 'title': 78202,
 'imdb': 38047,
 'reviews': 64767,
 'different': 21388,
 'faces': 27313,
 'exploitative': 26983,
 'serious': 68795,
 'cheap': 13823,
 'cheesy': 13924,
 'underlying': 80908,
 'moral': 51170,
 'message': 49466,
 'strange': 74049,
 'brew': 10592,
 'know': 43020,
 'why': 85123,
 'terms': 77115,
 'yes': 86589,
 'gariazzo': 31176,
 'trying': 79795,
 'earn': 24117,
 'fast': 27793,
 'buck': 11116,
 'able': 1480,
 'shoestring': 69668,
 'budget': 11161,
 'told': 78360,
 'atmospheric': 5636,
 'overall': 55722,
 'committed': 15998,
 'roles': 65615,
 'open': 55017,
 'may': 48449,
 'discover': 21862,
 'two': 80204,
 'three': 77724,
 'things': 77572,
 'please': 58943,
 'future': 30747,
 'writers': 86135,
 'producers': 60635,
 'directors': 21669,
 'learn': 44482,
 'never': 53118,
 'such': 74733,
 'bold': 9592,
 'original': 55289,
 'constantly': 16815,
 'step': 73577,
 'fantasy': 27641,
 'safely': 66590,
 'avoided': 6089,
 'something': 71886,
 'daring': 19320,
 'oh': 54688,
 'am': 3422,
 'sure': 75274,
 'happen': 34696,
 'stardust': 73302,
 'unexpected': 81125,
 'twist': 80182,
 'involve': 40000,
 'smallest': 71172,
 'part': 56771,
 'performed': 57626,
 'talent': 76206,
 'fills': 28517,
 'awe': 6140,
 'creators': 18078,
 'de': 19559,
 'niro': 53501,
 'performs': 57630,
 'energy': 25423,
 'simply': 70326,
 'steals': 73471,
 'each': 24077,
 'michelle': 49684,
 'pfeiffer': 58000,
 'perfect': 57601,
 'witch': 85565,
 'claire': 14832,
 'danes': 19219,
 'wonderful': 85757,
 'choice': 14305,
 'loving': 46184,
 'yvaine': 86854,
 'names': 52427,
 'outstanding': 55667,
 'filling': 28513,
 'everyone': 26473,
 'once': 54885,
 'again': 2540,
 'neil': 52933,
 'gaiman': 30890,
 'little': 45554,
 'invented': 39922,
 'universe': 81413,
 'pre': 59980,
 'screening': 67988,
 'today': 78296,
 'day': 19507,
 'official': 54630,
 'release': 63783,
 'hope': 36800,
 'success': 74709,
 'tense': 77038,
 'moments': 50837,
 'tender': 76990,
 'frivolities': 30363,
 'captain': 12380,
 'shakespeare': 69078,
 'passion': 56890,
 'lamia': 43875,
 'impressive': 38327,
 'number': 54079,
 'entertaining': 25659,
 '2007': 532,
 'enjoy': 25513,
 '11': 108,
 'peace': 57198,
 'complete': 16159,
 'justice': 41649,
 'exceptional': 26643,
 'important': 38277,
 'cut': 18838,
 'blanca': 8948,
 'alba': 2944,
 'essentially': 26190,
 'mushed': 52027,
 'subplots': 74594,
 'major': 47161,
 'elements': 24794,
 'eliminated': 24841,
 'clara': 14879,
 'clairvoyance': 14835,
 'extremely': 27167,
 'downplayed': 23113,
 'making': 47194,
 'seem': 68370,
 'shallow': 69108,
 'powers': 59881,
 'people': 57523,
 'turn': 80016,
 'key': 42395,
 'no': 53558,
 'lady': 43721,
 'relationship': 63762,
 'between': 8327,
 'esteban': 26208,
 'pedro': 57312,
 'tercero': 77083,
 'third': 77595,
 'son': 71919,
 'thus': 77867,
 'comes': 15866,
 'segundo': 68419,
 'second': 68267,
 'connections': 16641,
 'grandson': 33112,
 'pancha': 56397,
 'garcía': 31144,
 'recognize': 63116,
 'chopped': 14353,
 'half': 34365,
 'importance': 38275,
 'fundamental': 30611,
 'stripped': 74228,
 'called': 11986,
 'house': 37058,
 'spirits': 72631,
 'generations': 31541,
 'supposed': 75224,
 'revolve': 64820,
 'corner': 17371,
 'line': 45364,
 'stated': 73382,
 'novel': 53948,
 'unjustly': 81427,
 'relegates': 63791,
 'mere': 49357,
 'backdrop': 6362,
 'hadn': 34245,
 'read': 62823,
 'guessed': 33776,
 'sappy': 67029,
 'based': 7144,
 'rich': 64966,
 'exceptionally': 26644,
 'horrible': 36885,
 'barely': 6976,
 'put': 61579,
 'murder': 51949,
 'victims': 83090,
 'turns': 80034,
 'massacred': 48128,
 'chance': 13524,
 'missed': 50416,
 'crucial': 18442,
 'since': 70356,
 'slight': 70976,
 'coma': 15812,
 'box': 10187,
 'lured': 46488,
 'crude': 18457,
 'images': 38004,
 'bondage': 9688,
 'torture': 78667,
 'promises': 60788,
 'euro': 26344,
 'trash': 79192,
 'sexy': 68973,
 'flick': 29126,
 'feeling': 28051,
 'quarter': 61789,
 'left': 44601,
 'likely': 45237,
 'pg': 58016,
 '13': 156,
 'addition': 2059,
 'planet': 58794,
 'apes': 4432,
 'friend': 30294,
 'bottle': 10061,
 'hard': 34743,
 'need': 52841,
 'dressed': 23361,
 'kill': 42596,
 'brian': 10605,
 'depalma': 20540,
 'absolute': 1579,
 'thrill': 77739,
 'suspense': 75421,
 'style': 74459,
 'remains': 63872,
 'unrivaled': 81735,
 'bum': 11327,
 'hollywood': 36519,
 'claim': 14825,
 ...}

### Classify
##### Run a Logistic regression

In [240]:
logreg_model = LogisticRegression(random_state=11, max_iter=10000)
logreg_model.fit(X_train_features, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [241]:
# Report of metrics
print('Metrics of training:\n'+       classification_report(y_train, logreg_model.predict(X_train_features), digits=4))
print('Metrics of testing:\n'+      classification_report(y_test, logreg_model.predict(X_test_features), digits=4))

Metrics of training:
              precision    recall  f1-score   support

           0     0.9974    0.9975    0.9975     17500
           1     0.9975    0.9974    0.9975     17500

    accuracy                         0.9975     35000
   macro avg     0.9975    0.9975    0.9975     35000
weighted avg     0.9975    0.9975    0.9975     35000

Metrics of testing:
              precision    recall  f1-score   support

           0     0.8908    0.8915    0.8911      7500
           1     0.8914    0.8907    0.8910      7500

    accuracy                         0.8911     15000
   macro avg     0.8911    0.8911    0.8911     15000
weighted avg     0.8911    0.8911    0.8911     15000

In [284]:
# add data to the result table
model_search_result = model_search_result.append({'Model' : logreg_model, 
                           'F1 test' : f1_score(y_train, logreg_model.predict(X_train_features)), 
                            'F1 train' : f1_score(y_test, logreg_model.predict(X_test_features)) 
                           }, ignore_index=True )

model_search_result

                                               Model   F1 test  F1 train
0  LogisticRegression(C=1.0, class_weight=None, d...  0.997486  0.891023

##### Grid search cross validation

In [246]:
hyperparams_log_reg = {
    'C': [0.001,0.01,0.1,1,10,100], 
}

logreg_model_cross_valid=LogisticRegression(random_state=11, max_iter=4000)
logreg_cv = GridSearchCV(logreg_model_cross_valid, hyperparams_log_reg, scoring ='f1', cv=5, return_train_score=True )
logreg_cv.fit(X_train_features, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=4000, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=11, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='f1', verbose=0)

In [249]:
logreg_cv.best_score_

0.8910708045280765

#### Results Cross Validation

In [252]:

logreg_cv.cv_results_
pd.concat(
    [pd.DataFrame(logreg_cv.cv_results_["params"]),
     pd.DataFrame(logreg_cv.cv_results_["mean_test_score"],
                  columns=["f1"])]
    ,axis=1)

         C        f1
0    0.001  0.855083
1    0.010  0.886949
2    0.100  0.891071
3    1.000  0.882905
4   10.000  0.875659
5  100.000  0.871657

In [253]:
tuned_baseline_model = logreg_cv.best_estimator_
tuned_baseline_model

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=4000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

##### Second tuning hyperparam C

In [254]:
hyperparams_log_reg = {
    'C': [0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11], 
}

logreg_cv1 = GridSearchCV(logreg_model_cross_valid, hyperparams_log_reg, scoring ='f1', cv=5, return_train_score=True )
logreg_cv1.fit(X_train_features, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=4000, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=11, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='f1', verbose=0)

In [267]:
tuned_baseline_model1 = logreg_cv1.best_estimator_
tuned_baseline_model1

LogisticRegression(C=0.06, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=4000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [268]:
logreg_cv1.best_score_

0.8928416926159259

#####  Results second tuning

In [269]:

pd.concat(
    [pd.DataFrame(logreg_cv1.cv_results_["params"]),
     pd.DataFrame(logreg_cv1.cv_results_["mean_test_score"],
                  columns=["f1"])]
    ,axis=1)

      C        f1
0  0.04  0.892198
1  0.05  0.892645
2  0.06  0.892842
3  0.07  0.892374
4  0.08  0.891807
5  0.09  0.891254
6  0.10  0.891071
7  0.11  0.890678

### Result of Cross validation with 5 folds

In [270]:
result_cv = pd.DataFrame(columns = ['train C','F1-score(train)','test C', 'F1-score(test)'], index = range(0,5))
for splitN in range(5):
    result_cv['F1-score(train)'][splitN] = logreg_cv1.cv_results_['split'+str(splitN)+'_train_score'].max()
    result_cv['F1-score(test)'][splitN] = logreg_cv1.cv_results_['split'+str(splitN)+'_test_score'].max()
    result_cv['train C'][splitN] = logreg_cv1.cv_results_['params'][np.argmax(logreg_cv1.cv_results_['split'+str(splitN)+'_train_score'])]
    result_cv['test C'][splitN] = logreg_cv1.cv_results_['params'][np.argmax(logreg_cv1.cv_results_['split'+str(splitN)+'_test_score'])]


result_cv

       train C F1-score(train)       test C F1-score(test)
0  {'C': 0.11}        0.975653  {'C': 0.04}        0.89031
1  {'C': 0.11}        0.975154  {'C': 0.04}       0.886357
2  {'C': 0.11}        0.974642  {'C': 0.07}        0.89562
3  {'C': 0.11}        0.975021  {'C': 0.06}       0.894863
4  {'C': 0.11}        0.974876  {'C': 0.05}       0.899196

In [271]:
logreg_cv1.cv_results_

{'mean_fit_time': array([ 8.24298935,  8.36240463,  9.32571292,  9.80029607, 10.35570083,
        11.20198812, 11.2698411 , 11.65905175]),
 'std_fit_time': array([0.93032574, 0.52249903, 0.83451141, 0.38445516, 0.89630058,
        0.38327872, 0.6599227 , 0.73432435]),
 'mean_score_time': array([0.00997415, 0.01056552, 0.01036944, 0.01017451, 0.01077175,
        0.01037259, 0.01117034, 0.01136932]),
 'std_score_time': array([0.00063151, 0.00185171, 0.00205605, 0.00116381, 0.00171568,
        0.00184995, 0.0009771 , 0.00223857]),
 'param_C': masked_array(data=[0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.04},
  {'C': 0.05},
  {'C': 0.06},
  {'C': 0.07},
  {'C': 0.08},
  {'C': 0.09},
  {'C': 0.1},
  {'C': 0.11}],
 'split0_test_score': array([0.89030975, 0.89008958, 0.89002703, 0.88901537, 0.88958452,
        0.88854093, 0.8883509 , 0.88781321]),
 'split1_test_score': array([0.88635716, 0.88537662, 0.88556363, 0.88480182, 0.88445078,
        0.8837541 , 0.88346883, 0.88286489]),
 'split2_test_score': array([0.89296897, 0.89413773, 0.89530583, 0.89562002, 0.89445235,
        0.89480427, 0.89426498, 0.89398036]),
 'split3_test_score': array([0.8935689 , 0.894424  , 0.89486345, 0.89401443, 0.89287733,
        0.89250354, 0.89316542, 0.89272573]),
 'split4_test_score': array([0.89778655, 0.89919639, 0.89844852, 0.89841986, 0.89767114,
        0.89666855, 0.8961039 , 0.89600677]),
 'mean_test_score': array([0.89219827, 0.89264487, 0.89284169, 0.8923743 , 0.89180722,
        0.89125428, 0.8910708 , 0.89067819]),
 'std_test_score': array([0.00377853, 0.00464055, 0.00452744, 0.00486618, 0.00450744,
        0.00462801, 0.00458498, 0.00474861]),
 'rank_test_score': array([4, 2, 1, 3, 5, 6, 7, 8]),
 'split0_train_score': array([0.95465547, 0.95947917, 0.96357227, 0.96691242, 0.96899722,
        0.97216579, 0.97411765, 0.97565323]),
 'split1_train_score': array([0.95406386, 0.95915463, 0.96360596, 0.96710807, 0.9695135 ,
        0.97178683, 0.97366264, 0.97515417]),
 'split2_train_score': array([0.9537564 , 0.95820874, 0.96179455, 0.96513657, 0.96801994,
        0.97053269, 0.97268578, 0.97464246]),
 'split3_train_score': array([0.95375187, 0.9586111 , 0.96268018, 0.96585435, 0.96876673,
        0.97116345, 0.97284374, 0.97502141]),
 'split4_train_score': array([0.9535868 , 0.95845349, 0.96242744, 0.96602806, 0.96841281,
        0.97103153, 0.97306733, 0.97487616]),
 'mean_train_score': array([0.95396288, 0.95878143, 0.96281608, 0.9662079 , 0.96874204,
        0.97133606, 0.97327543, 0.97506949]),
 'std_train_score': array([0.00037907, 0.00046704, 0.00069408, 0.00072274, 0.00050807,
        0.00057612, 0.00053602, 0.00033763])}

### Choose the best model

In [277]:
baseline_model=LogisticRegression(C=0.06, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=4000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [278]:
baseline_model.fit(X_train_features, y_train)

LogisticRegression(C=0.06, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=4000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#### Report of metrics

In [281]:
# Report of metrics
print('Metrics of training:\n'+       classification_report(y_train, baseline_model.predict(X_train_features), digits=4))
print('Metrics of testing:\n'+      classification_report(y_test, baseline_model.predict(X_test_features), digits=4))

Metrics of training:
              precision    recall  f1-score   support

           0     0.9629    0.9569    0.9599     17500
           1     0.9571    0.9631    0.9601     17500

    accuracy                         0.9600     35000
   macro avg     0.9600    0.9600    0.9600     35000
weighted avg     0.9600    0.9600    0.9600     35000

Metrics of testing:
              precision    recall  f1-score   support

           0     0.9018    0.8941    0.8980      7500
           1     0.8950    0.9027    0.8988      7500

    accuracy                         0.8984     15000
   macro avg     0.8984    0.8984    0.8984     15000
weighted avg     0.8984    0.8984    0.8984     15000

In [285]:
# add data to the result table
model_search_result = model_search_result.append({'Model' : baseline_model, 
                           'F1 test' : f1_score(y_train, baseline_model.predict(X_train_features)), 
                            'F1 train' : f1_score(y_test, baseline_model.predict(X_test_features)) 
                           }, ignore_index=True )

model_search_result

                                               Model   F1 test  F1 train
0  LogisticRegression(C=1.0, class_weight=None, d...  0.997486  0.891023
1  LogisticRegression(C=0.06, class_weight=None, ...  0.960125  0.898832